### ISSUE TITLE
'import logging' failure

### ISSUE THREAD

**Issue by Narven** [craigemery/vim-autotag#22]
when I try to run vim im getting:

```
Error detected while processing /Users/pedromsluz/.vim/bundle/vim-autotag/plugin/autotag.vim:
line   25:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/pedromsluz/.vim/bundle/vim-autotag/plugin/autotag.py", line 11, in <module>
    import logging
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Press ENTER or type command to continue
```

python --version
Python 2.7.14

**Comment by craigemery** [comment]
I've Googled this and it's not my code. Are you using a virtual env? If so & you've upgraded your Python you need to re-create the env. But this isn't in my code so I can't fix it.
