### ISSUE TITLE
Broken in macOS with python 3.8

### ISSUE THREAD

**Issue by kitop** [craigemery/vim-autotag#33]
After upgrading to latest macOS, and upgrading vim via hombrew, it installed latest python3, which is 3.8.

With that, vim-autotag raises an error when starting vim:
```
Error detected while processing /Users/kito/dotfiles/vim/bundle/vim-autotag/plugin/autotag.vim:
line   24:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kito/dotfiles/vim/bundle/vim-autotag/plugin/autotag.py", line 57, in <module>
    fix_multiprocessing()
  File "/Users/kito/dotfiles/vim/bundle/vim-autotag/plugin/autotag.py", line 54, in fix_multiprocessing
    mp.set_executable(exes[0])
IndexError: list index out of range
```

In python 3.8, `spawn` start method is now used by default for macOS. See https://docs.python.org/3/whatsnew/3.8.html#multiprocessing

Related python issues:
- https://bugs.python.org/issue33725
- https://bugs.python.org/issue40106

When looking at the code, the new default now doesn't satisfy the condition in line 43:
https://github.com/craigemery/vim-autotag/blob/dcd9ef508eaa4b536e9bb8f6560553720bec5c37/plugin/autotag.py#L37-L54

And when trying to look for executables, as the lookup is very windows-based, it returns an empty array for macOS, and fails in line 54.

**Comment by craigemery** [comment]
Can you show me the path to your Python executable in your PATH?

**Comment by kitop** [comment]
In PATH`/usr/local/opt/python@3.8/bin`, full executable: `/usr/local/opt/python@3.8/bin/python3`

That's installed automatically with homebrew when installing the vim formula. One thing to note is that python 3.8 is not the default in homebrew (3.7 is), hence why not in `/usr/local/bin` directly. But vim formula [depends on python@3.8](https://formulae.brew.sh/formula/vim), so that's installed specifially for it.
```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May  6 2020 06:17:56)
macOS version
Included patches: 1-700
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl              +title
-clientserver      +job               +persistent_undo   -toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua               +ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.15 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.30.2_1/lib/perl5/5.30.2/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/config-3.8-darwin -lpython3.8 -framework CoreFoundation  -lruby.2.7
```

**Comment by craigemery** [comment]
So with start method spawn we need to find the Python executable.
I've been searching sys.path for files called python*.exe.
On macOS, the executables do not have a .exe suffix.
In Vim, the sys.executable isn't python, it's vim.
But we can look at its suffix to know what suffix to look for.

Try patching fix_multiprocessing to look like this:

```python
def fix_multiprocessing():
    """ Find a good Python executable to use for multiprocessing.Process """
    try:
        mp.set_executable
    except AttributeError:
        return
    if mp.get_start_method() != 'spawn':
        # Only need to fix the executable when start method is spawn
        # Most Linux implementations have "fork"
        return
    suff = os.path.splitext(sys.executable)[1]
    exes = glob.glob(os.path.join(sys.exec_prefix, "python*" % suff))
    win = [exe for exe in exes if exe.endswith("w" % suff)]
    if win:
        # In Windows pythonw.exe is best
        mp.set_executable(win[0])
    elif exes:
        # This is bad, for now pick the first one
        mp.set_executable(exes[0])
```

**Comment by craigemery** [comment]
Error in code snippet, I updated it in place.

**Comment by kitop** [comment]
Unfortunately, that's still not working, due to the same error. But I think the cause now is different, due to a missing `bin` when looking for the file.
```
>>> glob.glob(os.path.join(sys.exec_prefix, "python*%s" % suff))
[]
>>> glob.glob(os.path.join(sys.exec_prefix, "bin/python*%s" % suff))
['/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/bin/python3.8']
```

Adding that `bin` makes it work, but of course will break it for Windows.

**Comment by craigemery** [comment]
Ah, but we're globbing, so we can glob both, it'll be fine.

Craig

**Comment by craigemery** [comment]
pushed, after testing on Windows and Mojave. ;-)

**Comment by kitop** [comment]
Thanks for the quick fix! Confirmed it Works in Catalina with 3.8

**Comment by craigemery** [comment]
Is everything working? #34 is seeing weird spawn / fork issues on macOS.

**Comment by kitop** [comment]
I saw a similar error when `:wq` a file, and couldn't fully read the error message because vim exited quickly. Thought it was unrelated to this plugin, but another 3.8 spawn weirdness.
I now cannot reproduce consistently. Will report again if I keep encountering and have any more info.
